### ISSUE TITLE
manage.py migrate fails for vanilla installation 

### ISSUE THREAD

**Issue by jerzyk** [samluescher/django-form-designer#30]
When installing app for the new project, `./manage.py migrate` fails.

```

$ ./manage.py migrate
Running migrations for register:
- Nothing to migrate.
 - Loading initial data for register.
No fixtures found.
Running migrations for form_designer:
 - Migrating forwards to 0007_auto__add_field_formdefinition_mail_uploaded_files.
 > form_designer:0001_initial
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_manager(settings)
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/south/management/commands/migrate.py", line 105, in handle
    ignore_ghosts = ignore_ghosts,
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/south/migration/__init__.py", line 191, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/south/migration/migrators.py", line 221, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/south/migration/migrators.py", line 292, in migrate_many
    result = self.migrate(migration, database)
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/south/migration/migrators.py", line 125, in migrate
    result = self.run(migration)
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/south/migration/migrators.py", line 99, in run
    return self.run_migration(migration)
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/south/migration/migrators.py", line 82, in run_migration
    south.db.db.execute_deferred_sql()
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/south/db/generic.py", line 184, in execute_deferred_sql
    self.execute(sql)
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/south/db/generic.py", line 150, in execute
    cursor.execute(sql, params)
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/django/db/backends/util.py", line 34, in execute
    return self.cursor.execute(sql, params)
  File "/Users/jerzyk/Projects/Envs/egf2012/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
    return self.cursor.execute(query, args)
django.db.utils.DatabaseError: relation "cms_cmsplugin" does not exist
```

most probably because there are no `django-cms` in this project.

**Comment by ringemup** [comment]
Is Django-CMS a requirement for this app?

**Comment by jerzyk** [comment]
actually not...

**Comment by samluescher** [comment]
Refactoring: CMS plugins have been moved to contrib package. Removed all references to CMS from migrations. Please try installing again from current master.
