### ISSUE TITLE
Problem while installing django-form-designer

### ISSUE THREAD

**Issue by laparn** [samluescher/django-form-designer#41]
Hello,

I am testing and did the setup. I am trying to use django-form-designer from within django cms. When I am adding a form to a page, I get the following error :

Caught DatabaseError while rendering: relation "form_designer_formdefinition" does not exist LINE 1: ...rm_designer_formdefinition"."display_logged" FROM "form_desi... ^ 

It looks like I have pb in the database configuration. In my settings.py, I have just added the line form_designer.contrib.cms_plugins.form_designer_form in the INSTALLED_APPS section and     "/usr/local/lib/python2.7/dist-packages/form_designer/static", in my STATICFILE_DIRS section.

Then I have syncd and migrate with manage.py.

Do I have something more to do, for having all database tables correctly built ?

Regards,

Arnaud Laprévote

**Comment by laparn** [comment]
So I have added form_designer also to my INSTALLED_APPS. Then I manage.py syncdb (ok). And I have manage.py migrate => I have the following error :
....
Running migrations for form_designer:
- Migrating forwards to 0008_auto__add_formvalue__del_field_formlog_data__add_field_formlog_created.
  > form_designer:0001_initial
  Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_manager(settings)
  File "/usr/lib/pymodules/python2.7/django/core/management/**init**.py", line 438, in execute_manager
    utility.execute()
  File "/usr/lib/pymodules/python2.7/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/pymodules/python2.7/django/core/management/base.py", line 191, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/usr/lib/pymodules/python2.7/django/core/management/base.py", line 220, in execute
    output = self.handle(_args, *_options)
  File "/usr/lib/pymodules/python2.7/south/management/commands/migrate.py", line 105, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/lib/pymodules/python2.7/south/migration/**init**.py", line 191, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 221, in migrate_many
    result = migrator.**class**.migrate_many(migrator, target, migrations, database)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 292, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 125, in migrate
    result = self.run(migration)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 93, in run
    south.db.db.current_orm = self.orm(migration)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 246, in orm
    return migration.orm()
  File "/usr/lib/pymodules/python2.7/south/utils.py", line 62, in method
    value = function(self)
  File "/usr/lib/pymodules/python2.7/south/migration/base.py", line 422, in orm
    return FakeORM(self.migration_class(), self.app_label())
  File "/usr/lib/pymodules/python2.7/south/orm.py", line 46, in FakeORM
    _orm_cache[args] = _FakeORM(*args)  
  File "/usr/lib/pymodules/python2.7/south/orm.py", line 125, in __init__
    self.models[name] = self.make_model(app_label, model_name, data)
  File "/usr/lib/pymodules/python2.7/south/orm.py", line 318, in make_model
    field = self.eval_in_context(code, app, extra_imports)
  File "/usr/lib/pymodules/python2.7/south/orm.py", line 229, in eval_in_context
    raise ValueError("Cannot import the required field '%s'" % value)
  ValueError: Cannot import the required field 'picklefield.fields.PickledObjectField'

**Comment by samluescher** [comment]
The version you're using requires django-picklefield. Either install that, or use current master, which removes that dependency.

**Comment by laparn** [comment]
Thanks Philomat. I get one step further. After having installed django-pickelfield (0.2), I get there :

arnaud@D3550:~/source/django-sites/sq2$ sudo python manage.py migrate form_designer
Running migrations for form_designer:
- Migrating forwards to 0010_initial.
  > form_designer:0008_auto__add_formvalue__del_field_formlog_data__add_field_formlog_created
  Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_manager(settings)
  File "/usr/lib/pymodules/python2.7/django/core/management/**init**.py", line 438, in execute_manager
    utility.execute()
  File "/usr/lib/pymodules/python2.7/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/pymodules/python2.7/django/core/management/base.py", line 191, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/usr/lib/pymodules/python2.7/django/core/management/base.py", line 220, in execute
    output = self.handle(_args, *_options)
  File "/usr/lib/pymodules/python2.7/south/management/commands/migrate.py", line 105, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/lib/pymodules/python2.7/south/migration/**init**.py", line 191, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 221, in migrate_many
    result = migrator.**class**.migrate_many(migrator, target, migrations, database)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 292, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 125, in migrate
    result = self.run(migration)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 99, in run
    return self.run_migration(migration)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 81, in run_migration
    migration_function()
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "/usr/local/lib/python2.7/dist-packages/form_designer/migrations/0008_auto__add_formvalue__del_field_formlog_data__add_field_formlog_created.py", line 34, in forwards
    db.delete_column('form_designer_formlog', 'data')
  File "/usr/lib/pymodules/python2.7/south/db/generic.py", line 699, in delete_column
    self.execute(self.delete_column_string % params, [])
  File "/usr/lib/pymodules/python2.7/south/db/generic.py", line 150, in execute
    cursor.execute(sql, params)
  File "/usr/lib/pymodules/python2.7/django/db/backends/util.py", line 34, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/pymodules/python2.7/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
    return self.cursor.execute(query, args)
  django.db.utils.DatabaseError: column "data" of relation "form_designer_formlog" does not exist
