### ISSUE TITLE
django.db.utils.DatabaseError: column "data" of relation "form_designer_formlog" does not exist

### ISSUE THREAD

**Issue by laparn** [samluescher/django-form-designer#42]
This is following the previous issue.
Thanks Philomat. I get one step further. After having installed django-pickelfield (0.2), I get there :

arnaud@D3550:~/source/django-sites/sq2$ sudo python manage.py migrate form_designer
Running migrations for form_designer:
- Migrating forwards to 0010_initial.
  > form_designer:0008_autoadd_formvaluedel_field_formlog_dataadd_field_formlog_created
  Traceback (most recent call last):
  File "manage.py", line 14, in
  execute_manager(settings)
  File "/usr/lib/pymodules/python2.7/django/core/management/init.py", line 438, in execute_manager
  utility.execute()
  File "/usr/lib/pymodules/python2.7/django/core/management/init.py", line 379, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/pymodules/python2.7/django/core/management/base.py", line 191, in run_from_argv
  self.execute(_args, *_options.dict)
  File "/usr/lib/pymodules/python2.7/django/core/management/base.py", line 220, in execute
  output = self.handle(_args, *_options)
  File "/usr/lib/pymodules/python2.7/south/management/commands/migrate.py", line 105, in handle
  ignore_ghosts = ignore_ghosts,
  File "/usr/lib/pymodules/python2.7/south/migration/init.py", line 191, in migrate_app
  success = migrator.migrate_many(target, workplan, database)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 221, in migrate_many
  result = migrator.class.migrate_many(migrator, target, migrations, database)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 292, in migrate_many
  result = self.migrate(migration, database)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 125, in migrate
  result = self.run(migration)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 99, in run
  return self.run_migration(migration)
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 81, in run_migration
  migration_function()
  File "/usr/lib/pymodules/python2.7/south/migration/migrators.py", line 57, in
  return (lambda: direction(orm))
  File "/usr/local/lib/python2.7/dist-packages/form_designer/migrations/0008_autoadd_formvaluedel_field_formlog_dataadd_field_formlog_created.py", line 34, in forwards
  db.delete_column('form_designer_formlog', 'data')
  File "/usr/lib/pymodules/python2.7/south/db/generic.py", line 699, in delete_column
  self.execute(self.delete_column_string % params, [])
  File "/usr/lib/pymodules/python2.7/south/db/generic.py", line 150, in execute
  cursor.execute(sql, params)
  File "/usr/lib/pymodules/python2.7/django/db/backends/util.py", line 34, in execute
  return self.cursor.execute(sql, params)
  File "/usr/lib/pymodules/python2.7/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
  return self.cursor.execute(query, args)
  django.db.utils.DatabaseError: column "data" of relation "form_designer_formlog" does not exist

**Comment by samluescher** [comment]
Please make sure you are using the current master. Additionally you might want to just reset the tables: 

```
$ python manage.py reset form_designer
```

**Comment by la-only** [comment]
Just make

$  python manage.py syncdb --all
