### ISSUE TITLE
pip insatll error

### ISSUE THREAD

**Issue by mnewsome** [samluescher/django-form-designer#43]
I'm getting the following error when using the pip install in a virtualenv,  Has this come up for anyone?  Am I missing something?

(venv)malcolm@ubuntu:~/projects/lawsite$ pip install git://github.com/philomat/django-form-designer.git#egg=django-form-designer
Downloading/unpacking django-form-designer from git://github.com/philomat/django-form-designer.git
Exception:
Traceback (most recent call last):
  File "/home/malcolm/projects/lawsite/venv/local/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/home/malcolm/projects/lawsite/venv/local/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/malcolm/projects/lawsite/venv/local/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/req.py", line 961, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/home/malcolm/projects/lawsite/venv/local/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/req.py", line 1073, in unpack_url
    return unpack_vcs_link(link, location, only_download)
  File "/home/malcolm/projects/lawsite/venv/local/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/download.py", line 293, in unpack_vcs_link
    vcs_backend.unpack(location)
  File "/home/malcolm/projects/lawsite/venv/local/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/vcs/**init**.py", line 225, in unpack
    self.obtain(location)
  File "/home/malcolm/projects/lawsite/venv/local/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/vcs/git.py", line 97, in obtain
    url, rev = self.get_url_rev()
  File "/home/malcolm/projects/lawsite/venv/local/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/vcs/git.py", line 183, in get_url_rev
    url, rev = super(Git, self).get_url_rev()
  File "/home/malcolm/projects/lawsite/venv/local/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/vcs/**init**.py", line 117, in get_url_rev
    url = self.url.split('+', 1)[1]
IndexError: list index out of range

Thanks!

**Comment by ghost** [comment]
I am also encountering this issue.

**Comment by driesdesmet** [comment]
There's a typo in the install instructions. It should be pip install git+git://..... There is a patch see issue #52
