### ISSUE TITLE
Migration 0008 fails on SQLite

### ISSUE THREAD

**Issue by aarcro** [samluescher/django-form-designer#48]
I had a problem running the 0008 migration on SQLite. When it hit the data migration part during dry-run it couldn't find the new fields:

```
    for log in FormLog.objects.all():
        log.set_data(log.tmp_data)
        log.save()
```

I fixed it by adding this:

```
    if not db.dry_run:
        for log in FormLog.objects.all():
            log.set_data(log.tmp_data)
            log.save()
```

**Comment by romlok** [comment]
I'm assuming that I had the same problem (since I'm also using sqlite, and didn't have the other error mentioned). FTR, my error was:

```
DatabaseError: no such column: form_designer_formlog.created_by_id
```

I've split apart the schema changes and data migration in raumkraut/django-form-designer@1e67fa755e16d5e216d9d1e31702eac2c6f1ff24 (0008 and 0008b), so that can be cherry-picked, to fix the problem without dry-run special-casing (which sounds dangerous to me!)...

**Comment by evildmp** [comment]
A similar thing hit me. I'm not using SQLite though:

```
$ python manage.py migrate form_designer 
/home/daniele/consolationnight-dev/lib/python2.6/site-packages/django/conf/__init__.py:75: DeprecationWarning: The ADMIN_MEDIA_PREFIX setting has been removed; use STATIC_URL instead.
  "use STATIC_URL instead.", DeprecationWarning)
/home/daniele/consolationnight-dev/lib/python2.6/site-packages/mptt/models.py:305: DeprecationWarning: Implicit manager CMSPlugin.tree will be removed in django-mptt 0.6.  Explicitly define a TreeManager() on your model to remove this warning.
  DeprecationWarning
Running migrations for form_designer:
 - Migrating forwards to 0008_auto__add_formvalue__del_field_formlog_data__add_field_formlog_created.
 > form_designer:0001_initial
 > form_designer:0002_auto__chg_field_formdefinitionfield_initial
 > form_designer:0003_auto__add_field_formdefinition_display_logged
 > form_designer:0004_auto__add_field_formdefinition_body
 > form_designer:0005_auto__add_field_formdefinition_require_hash__add_field_formdefinition_
 > form_designer:0006_auto__add_field_formdefinition_save_uploaded_files
 > form_designer:0007_auto__add_field_formdefinition_mail_uploaded_files
 > form_designer:0008_auto__add_formvalue__del_field_formlog_data__add_field_formlog_created
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/south/management/commands/migrate.py", line 108, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/south/migration/__init__.py", line 213, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/south/migration/migrators.py", line 235, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/south/migration/migrators.py", line 310, in migrate_many
    result = self.migrate(migration, database)
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration)
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/south/migration/migrators.py", line 106, in run
    dry_run.run_migration(migration)
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/south/migration/migrators.py", line 191, in run_migration
    self._run_migration(migration)
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/south/migration/migrators.py", line 178, in _run_migration
    raise exceptions.FailedDryRun(migration, sys.exc_info())
south.exceptions.FailedDryRun:  ! Error found during dry run of '0008_auto__add_formvalue__del_field_formlog_data__add_field_formlog_created'! Aborting.
Traceback (most recent call last):
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/south/migration/migrators.py", line 175, in _run_migration
    migration_function()
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "/home/daniele/consolationnight-dev/src/django-form-designer/form_designer/migrations/0008_auto__add_formvalue__del_field_formlog_data__add_field_formlog_created.py", line 29, in forwards
    for log in FormLog.objects.all():
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/django/db/models/query.py", line 892, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/home/daniele/consolationnight-dev/lib/python2.6/site-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/pymodules/python2.6/MySQLdb/cursors.py", line 166, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/pymodules/python2.6/MySQLdb/connections.py", line 35, in defaulterrorhandler
    raise errorclass, errorvalue
DatabaseError: (1054, "Unknown column 'form_designer_formlog.created_by_id' in 'field list'")
```

**Comment by samluescher** [comment]
Fixed in current master.
