### ISSUE TITLE
Migration fails to load models - Django 1.8.5 Django-CMS 3.1

### ISSUE THREAD

**Issue by source3** [samluescher/django-form-designer#98]
The following error occurs running 'python manage.py migrate'.  Upgrading from Django 1.5/django-cms 2.4.  I tired migrating from south as explained in https://docs.djangoproject.com/en/1.8/topics/migrations/#upgrading-from-south and https://docs.djangoproject.com/en/1.8/topics/migrations/#libraries-third-party-apps.  Did not work.  Same error.

Any suggestions or solutions is much appreciated.

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/ebs/localdealsmagazine/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 351, in execute_from_command_line
    utility.execute()
  File "/ebs/localdealsmagazine/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 325, in execute
    django.setup()
  File "/ebs/localdealsmagazine/local/lib/python2.7/site-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/ebs/localdealsmagazine/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/ebs/localdealsmagazine/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/ebs/localdealsmagazine/local/lib/python2.7/site-packages/form_designer/contrib/cms_plugins/form_designer_form/models.py", line 1, in <module>
    from form_designer.models import FormDefinition
  File "/ebs/localdealsmagazine/local/lib/python2.7/site-packages/form_designer/models.py", line 19, in <module>
    User = get_user_model()
  File "/ebs/localdealsmagazine/local/lib/python2.7/site-packages/django/contrib/auth/**init**.py", line 150, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/ebs/localdealsmagazine/local/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/ebs/localdealsmagazine/local/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

settings.py:
INSTALLED_APPS = (
   ...
    'picklefield',
    'form_designer.contrib.cms_plugins.form_designer_form', 
    'form_designer',  
    ...
)

MIDDLEWARE_CLASSES = (
    ...
    'form_designer.middleware.RedirectMiddleware',
)

**Comment by source3** [comment]
Fixed.  Warning, I have not fully tested the fix below.

Django 1.8 
- uses ugettext_lazy not ugettext.  Replaced all occurances of ugettext with ugettext_lazy in cms_plugins.py, settings.py, forms.py, models.py, admin.py, and views.py
- replaced get_user_model with auth_user_model in models.py
- ModelForm requires either 'fields' or 'exclude' in the meta.  Added fields =  '**all**' in forms.py where two classes subclass from ModelForm.
- removed the middleware class as shown above.  
- Copied ../migrations to ../migrations_south.  Then removed all files excecpt '_ _init.py_ _' in the migrations folder.

Then ran 'python mange.py makemigrations' then 'python migrate.py form_designer'. 

I submitted patches for the above files.  Not to good with github so I hope I proposed the changes correctly.

**Comment by andreav** [comment]
Same here.
Django==1.8.7 + django-cms==3.2.0

Any chance the patch will be merged?
Thanks.

**Comment by theblackcat102** [comment]
Same here, Please merge the patch as soon as possible

**Comment by barseghyanartur** [comment]
Guys, seriously, don't you see the project is dead? Last commit has been done about 3 years ago (same goes for the last issue closed). Either (1) fork and register on PyPI under different name or (2) switch to [another package](https://djangopackages.org/grids/g/form-builder/).
